FROM phusion/passenger-ruby22

RUN mkdir -p /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN ls /app
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES 'true'
RUN bundle install --jobs 20 --retry 5 --verbose
EXPOSE 5000
CMD ["./start_production.sh"]
